version: "3.9"
services:

  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor:v0.36.0
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      # - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8089:8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    expose:
      - "9090"
    depends_on:
      - consul
    restart: always
    networks:
      - promnet

  consul:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    expose:
      - "8500" # HTTP API|UI
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

networks:
  consul:
    driver: bridge
  promnet:
    driver: bridge