global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  # Consul
  - job_name: consul
    consul_sd_configs:
      - server: consul:8500
        datacenter: dc1
        tags:
        - foo

  # Self
  - job_name: "prometheus-server"
    static_configs:
      - targets:
          - "localhost:9090"

  # cAdvisor exports metrics for *all* containers running on this host
  - job_name: cadvisor
    static_configs:
      - targets:
          - "cadvisor:8080"