version: "3.9"
services:
  node-exporter:
    build: 
      context: .
      args:
        CONSUL_IP: ${CONSUL_IP}
    restart: always
    expose:
      - "9100"
    networks:
      - prometheus-auto-discovery_promnet
    # ports:
    #   - 9100:9100/tcp

networks:
  prometheus-auto-discovery_promnet:
    external: true