version: "3.9"
services:
  node-exporter:
    build: 
      context: .
      args:
        CONSUL_IP: ${CONSUL_IP}
    restart: always
    networks:
      - prometheus-auto-discovery_promnet
    ports:
    - 9101:9100/tcp

networks:
  prometheus-auto-discovery_promnet:
    external: true